# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#capitalize first letter of each word? Model names seem to be doing that.
m1 = ModelInfo.create(make: "Ford", model: "Mustang")
m2 = ModelInfo.create(make: "Toyota", model: "Celica")
m3 = ModelInfo.create(make: "Nissan", model: "Maxima")
m4 = ModelInfo.create(make: "Toyota", model: "Camry")
m5 = ModelInfo.create(make: "Chevrolet", model: "Malibu")
m6 = ModelInfo.create(make: "BMW", model: "528i")
m7 = ModelInfo.create(make: "Honda", model: "CRV")
m8 = ModelInfo.create(make: "Nissan", model: "Pathfinder")
m9 = ModelInfo.create(make: "Ford", model: "Expedition")
m8 = ModelInfo.create(make: "Chevrolet", model: "Tahoe")
m9 = ModelInfo.create(make: "Volkswagen", model: "Passat TDI")
m10 = ModelInfo.create(make: "Volvo", model: "XC70" )
m10 = ModelInfo.create(make: "Honda", model: "Accord" )
m10 = ModelInfo.create(make: "Chevrolet", model: "Silverado" )
m10 = ModelInfo.create(make: "Honda", model: "Civic" )

c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )
c1 = CarItem.create(price:"", sold:false, mileage: 100,000, image_url:"", model_info_id: )